package ghostysoft.bleuuidexplorer;
/**
 * Created by ghosty on 2015/3/9.
 */

import java.util.HashMap;

public class CompanyIDs {
    private static HashMap<Integer, String> companies = new HashMap();

    static {
        companies.put(0x0000, "Ericsson Technology Licensing");
        companies.put(0x0001, "Nokia Mobile Phones");
        companies.put(0x0002, "Intel Corp.");
        companies.put(0x0003, "IBM Corp.");
        companies.put(0x0004, "Toshiba Corp.");
        companies.put(0x0005, "3Com");
        companies.put(0x0006, "Microsoft");
        companies.put(0x0007, "Lucent");
        companies.put(0x0008, "Motorola");
        companies.put(0x0009, "Infineon Technologies AG");
        companies.put(0x000A, "Cambridge Silicon Radio");
        companies.put(0x000B, "Silicon Wave");
        companies.put(0x000C, "Digianswer A/S");
        companies.put(0x000D, "Texas Instruments Inc.");
        companies.put(0x000E, "Parthus Technologies Inc.");
        companies.put(0x000F, "Broadcom Corporation");
        companies.put(0x0010, "Mitel Semiconductor");
        companies.put(0x0011, "Widcomm, Inc.");
        companies.put(0x0012, "Zeevo, Inc.");
        companies.put(0x0013, "Atmel Corporation");
        companies.put(0x0014, "Mitsubishi Electric Corporation");
        companies.put(0x0015, "RTX Telecom A/S");
        companies.put(0x0016, "KC Technology Inc.");
        companies.put(0x0017, "Newlogic");
        companies.put(0x0018, "Transilica, Inc.");
        companies.put(0x0019, "Rohde & Schwarz GmbH & Co. KG");
        companies.put(0x001A, "TTPCom Limited");
        companies.put(0x001B, "Signia Technologies, Inc.");
        companies.put(0x001C, "Conexant Systems Inc.");
        companies.put(0x001D, "Qualcomm");
        companies.put(0x001E, "Inventel");
        companies.put(0x001F, "AVM Berlin");
        companies.put(0x0020, "BandSpeed, Inc.");
        companies.put(0x0021, "Mansella Ltd");
        companies.put(0x0022, "NEC Corporation");
        companies.put(0x0023, "WavePlus Technology Co., Ltd.");
        companies.put(0x0024, "Alcatel");
        companies.put(0x0025, "NXP Semiconductors (formerly Philips Semiconductors)");
        companies.put(0x0026, "C Technologies");
        companies.put(0x0027, "Open Interface");
        companies.put(0x0028, "R F Micro Devices");
        companies.put(0x0029, "Hitachi Ltd");
        companies.put(0x002A, "Symbol Technologies, Inc.");
        companies.put(0x002B, "Tenovis");
        companies.put(0x002C, "Macronix International Co. Ltd.");
        companies.put(0x002D, "GCT Semiconductor");
        companies.put(0x002E, "Norwood Systems");
        companies.put(0x002F, "MewTel Technology Inc.");
        companies.put(0x0030, "ST Microelectronics");
        companies.put(0x0031, "Synopsys, Inc.");
        companies.put(0x0032, "Red-M (Communications) Ltd");
        companies.put(0x0033, "Commil Ltd");
        companies.put(0x0034, "Computer Access Technology Corporation (CATC)");
        companies.put(0x0035, "Eclipse (HQ Espana) S.L.");
        companies.put(0x0036, "Renesas Electronics Corporation");
        companies.put(0x0037, "Mobilian Corporation");
        companies.put(0x0038, "Terax");
        companies.put(0x0039, "Integrated System Solution Corp.");
        companies.put(0x003A, "Matsushita Electric Industrial Co., Ltd.");
        companies.put(0x003B, "Gennum Corporation");
        companies.put(0x003C, "BlackBerry Limited (formerly Research In Motion)");
        companies.put(0x003D, "IPextreme, Inc.");
        companies.put(0x003E, "Systems and Chips, Inc");
        companies.put(0x003F, "Bluetooth SIG, Inc");
        companies.put(0x0040, "Seiko Epson Corporation");
        companies.put(0x0041, "Integrated Silicon Solution Taiwan, Inc.");
        companies.put(0x0042, "CONWISE Technology Corporation Ltd");
        companies.put(0x0043, "PARROT AUTOMOTIVE SAS");
        companies.put(0x0044, "Socket Mobile");
        companies.put(0x0045, "Atheros Communications, Inc.");
        companies.put(0x0046, "MediaTek, Inc.");
        companies.put(0x0047, "Bluegiga");
        companies.put(0x0048, "Marvell Technology Group Ltd.");
        companies.put(0x0049, "3DSP Corporation");
        companies.put(0x004A, "Accel Semiconductor Ltd.");
        companies.put(0x004B, "Continental Automotive Systems");
        companies.put(0x004C, "Apple, Inc.");
        companies.put(0x004D, "Staccato Communications, Inc.");
        companies.put(0x004E, "Avago Technologies");
        companies.put(0x004F, "APT Ltd.");
        companies.put(0x0050, "SiRF Technology, Inc.");
        companies.put(0x0051, "Tzero Technologies, Inc.");
        companies.put(0x0052, "J&M Corporation");
        companies.put(0x0053, "Free2move AB");
        companies.put(0x0054, "3DiJoy Corporation");
        companies.put(0x0055, "Plantronics, Inc.");
        companies.put(0x0056, "Sony Ericsson Mobile Communications");
        companies.put(0x0057, "Harman International Industries, Inc.");
        companies.put(0x0058, "Vizio, Inc.");
        companies.put(0x0059, "Nordic Semiconductor ASA");
        companies.put(0x005A, "EM Microelectronic-Marin SA");
        companies.put(0x005B, "Ralink Technology Corporation");
        companies.put(0x005C, "Belkin International, Inc.");
        companies.put(0x005D, "Realtek Semiconductor Corporation");
        companies.put(0x005E, "Stonestreet One, LLC");
        companies.put(0x005F, "Wicentric, Inc.");
        companies.put(0x0060, "RivieraWaves S.A.S");
        companies.put(0x0061, "RDA Microelectronics");
        companies.put(0x0062, "Gibson Guitars");
        companies.put(0x0063, "MiCommand Inc.");
        companies.put(0x0064, "Band XI International, LLC");
        companies.put(0x0065, "Hewlett-Packard Company");
        companies.put(0x0066, "9Solutions Oy");
        companies.put(0x0067, "GN Netcom A/S");
        companies.put(0x0068, "General Motors");
        companies.put(0x0069, "A&D Engineering, Inc.");
        companies.put(0x006A, "MindTree Ltd.");
        companies.put(0x006B, "Polar Electro OY");
        companies.put(0x006C, "Beautiful Enterprise Co., Ltd.");
        companies.put(0x006D, "BriarTek, Inc");
        companies.put(0x006E, "Summit Data Communications, Inc.");
        companies.put(0x006F, "Sound ID");
        companies.put(0x0070, "Monster, LLC");
        companies.put(0x0071, "connectBlue AB");
        companies.put(0x0072, "ShangHai Super Smart Electronics Co. Ltd.");
        companies.put(0x0073, "Group Sense Ltd.");
        companies.put(0x0074, "Zomm, LLC");
        companies.put(0x0075, "Samsung Electronics Co. Ltd.");
        companies.put(0x0076, "Creative Technology Ltd.");
        companies.put(0x0077, "Laird Technologies");
        companies.put(0x0078, "Nike, Inc.");
        companies.put(0x0079, "lesswire AG");
        companies.put(0x007A, "MStar Semiconductor, Inc.");
        companies.put(0x007B, "Hanlynn Technologies");
        companies.put(0x007C, "A & R Cambridge");
        companies.put(0x007D, "Seers Technology Co., Ltd.");
        companies.put(0x007E, "Sports Tracking Technologies Ltd.");
        companies.put(0x007F, "Autonet Mobile");
        companies.put(0x0080, "DeLorme Publishing Company, Inc.");
        companies.put(0x0081, "WuXi Vimicro");
        companies.put(0x0082, "Sennheiser Communications A/S");
        companies.put(0x0083, "TimeKeeping Systems, Inc.");
        companies.put(0x0084, "Ludus Helsinki Ltd.");
        companies.put(0x0085, "BlueRadios, Inc.");
        companies.put(0x0086, "Equinux AG");
        companies.put(0x0087, "Garmin International, Inc.");
        companies.put(0x0088, "Ecotest");
        companies.put(0x0089, "GN ReSound A/S");
        companies.put(0x008A, "Jawbone");
        companies.put(0x008B, "Topcon Positioning Systems, LLC");
        companies.put(0x008C, "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)");
        companies.put(0x008D, "Zscan Software");
        companies.put(0x008E, "Quintic Corp");
        companies.put(0x008F, "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)");
        companies.put(0x0090, "Funai Electric Co., Ltd.");
        companies.put(0x0091, "Advanced PANMOBIL systems GmbH & Co. KG");
        companies.put(0x0092, "ThinkOptics, Inc.");
        companies.put(0x0093, "Universal Electronics, Inc.");
        companies.put(0x0094, "Airoha Technology Corp.");
        companies.put(0x0095, "NEC Lighting, Ltd.");
        companies.put(0x0096, "ODM Technology, Inc.");
        companies.put(0x0097, "ConnecteDevice Ltd.");
        companies.put(0x0098, "zero1.tv GmbH");
        companies.put(0x0099, "i.Tech Dynamic Global Distribution Ltd.");
        companies.put(0x009A, "Alpwise");
        companies.put(0x009B, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        companies.put(0x009C, "Colorfy, Inc.");
        companies.put(0x009D, "Geoforce Inc.");
        companies.put(0x009E, "Bose Corporation");
        companies.put(0x009F, "Suunto Oy");
        companies.put(0x00A0, "Kensington Computer Products Group");
        companies.put(0x00A1, "SR-Medizinelektronik");
        companies.put(0x00A2, "Vertu Corporation Limited");
        companies.put(0x00A3, "Meta Watch Ltd.");
        companies.put(0x00A4, "LINAK A/S");
        companies.put(0x00A5, "OTL Dynamics LLC");
        companies.put(0x00A6, "Panda Ocean Inc.");
        companies.put(0x00A7, "Visteon Corporation");
        companies.put(0x00A8, "ARP Devices Limited");
        companies.put(0x00A9, "Magneti Marelli S.p.A");
        companies.put(0x00AA, "CAEN RFID srl");
        companies.put(0x00AB, "Ingenieur-Systemgruppe Zahn GmbH");
        companies.put(0x00AC, "Green Throttle Games");
        companies.put(0x00AD, "Peter Systemtechnik GmbH");
        companies.put(0x00AE, "Omegawave Oy");
        companies.put(0x00AF, "Cinetix");
        companies.put(0x00B0, "Passif Semiconductor Corp");
        companies.put(0x00B1, "Saris Cycling Group, Inc");
        companies.put(0x00B2, "Bekey A/S");
        companies.put(0x00B3, "Clarinox Technologies Pty. Ltd.");
        companies.put(0x00B4, "BDE Technology Co., Ltd.");
        companies.put(0x00B5, "Swirl Networks");
        companies.put(0x00B6, "Meso international");
        companies.put(0x00B7, "TreLab Ltd");
        companies.put(0x00B8, "Qualcomm Innovation Center, Inc. (QuIC)");
        companies.put(0x00B9, "Johnson Controls, Inc.");
        companies.put(0x00BA, "Starkey Laboratories Inc.");
        companies.put(0x00BB, "S-Power Electronics Limited");
        companies.put(0x00BC, "Ace Sensor Inc");
        companies.put(0x00BD, "Aplix Corporation");
        companies.put(0x00BE, "AAMP of America");
        companies.put(0x00BF, "Stalmart Technology Limited");
        companies.put(0x00C0, "AMICCOM Electronics Corporation");
        companies.put(0x00C1, "Shenzhen Excelsecu Data Technology Co.,Ltd");
        companies.put(0x00C2, "Geneq Inc.");
        companies.put(0x00C3, "adidas AG");
        companies.put(0x00C4, "LG Electronics");
        companies.put(0x00C5, "Onset Computer Corporation");
        companies.put(0x00C6, "Selfly BV");
        companies.put(0x00C7, "Quuppa Oy.");
        companies.put(0x00C8, "GeLo Inc");
        companies.put(0x00C9, "Evluma");
        companies.put(0x00CA, "MC10");
        companies.put(0x00CB, "Binauric SE");
        companies.put(0x00CC, "Beats Electronics");
        companies.put(0x00CD, "Microchip Technology Inc.");
        companies.put(0x00CE, "Elgato Systems GmbH");
        companies.put(0x00CF, "ARCHOS SA");
        companies.put(0x00D0, "Dexcom, Inc.");
        companies.put(0x00D1, "Polar Electro Europe B.V.");
        companies.put(0x00D2, "Dialog Semiconductor B.V.");
        companies.put(0x00D3, "Taixingbang Technology (HK) Co,. LTD.");
        companies.put(0x00D4, "Kawantech");
        companies.put(0x00D5, "Austco Communication Systems");
        companies.put(0x00D6, "Timex Group USA, Inc.");
        companies.put(0x00D7, "Qualcomm Technologies, Inc.");
        companies.put(0x00D8, "Qualcomm Connected Experiences, Inc.");
        companies.put(0x00D9, "Voyetra Turtle Beach");
        companies.put(0x00DA, "txtr GmbH");
        companies.put(0x00DB, "Biosentronics");
        companies.put(0x00DC, "Procter & Gamble");
        companies.put(0x00DD, "Hosiden Corporation");
        companies.put(0x00DE, "Muzik LLC");
        companies.put(0x00DF, "Misfit Wearables Corp");
        companies.put(0x00E0, "Google");
        companies.put(0x00E1, "Danlers Ltd");
        companies.put(0x00E2, "Semilink Inc");
        companies.put(0x00E3, "inMusic Brands, Inc");
        companies.put(0x00E4, "L.S. Research Inc.");
        companies.put(0x00E5, "Eden Software Consultants Ltd.");
        companies.put(0x00E6, "Freshtemp");
        companies.put(0x00E7, "KS Technologies");
        companies.put(0x00E8, "ACTS Technologies");
        companies.put(0x00E9, "Vtrack Systems");
        companies.put(0x00EA, "Nielsen-Kellerman Company");
        companies.put(0x00EB, "Server Technology Inc.");
        companies.put(0x00EC, "BioResearch Associates");
        companies.put(0x00ED, "Jolly Logic, LLC");
        companies.put(0x00EE, "Above Average Outcomes, Inc.");
        companies.put(0x00EF, "Bitsplitters GmbH");
        companies.put(0x00F0, "PayPal, Inc.");
        companies.put(0x00F1, "Witron Technology Limited");
        companies.put(0x00F2, "Morse Project Inc.");
        companies.put(0x00F3, "Kent Displays Inc.");
        companies.put(0x00F4, "Nautilus Inc.");
        companies.put(0x00F5, "Smartifier Oy");
        companies.put(0x00F6, "Elcometer Limited");
        companies.put(0x00F7, "VSN Technologies, Inc.");
        companies.put(0x00F8, "AceUni Corp., Ltd.");
        companies.put(0x00F9, "StickNFind");
        companies.put(0x00FA, "Crystal Code AB");
        companies.put(0x00FB, "KOUKAAM a.s.");
        companies.put(0x00FC, "Delphi Corporation");
        companies.put(0x00FD, "ValenceTech Limited");
        companies.put(0x00FE, "Stanley Black and Decker");
        companies.put(0x00FF, "Typo Products, LLC");
        companies.put(0x0100, "TomTom International BV");
        companies.put(0x0101, "Fugoo, Inc.");
        companies.put(0x0102, "Keiser Corporation");
        companies.put(0x0103, "Bang & Olufsen A/S");
        companies.put(0x0104, "PLUS Location Systems Pty Ltd");
        companies.put(0x0105, "Ubiquitous Computing Technology Corporation");
        companies.put(0x0106, "Innovative Yachtter Solutions");
        companies.put(0x0107, "William Demant Holding A/S");
        companies.put(0x0108, "Chicony Electronics Co., Ltd.");
        companies.put(0x0109, "Atus BV");
        companies.put(0x010A, "Codegate Ltd");
        companies.put(0x010B, "ERi, Inc");
        companies.put(0x010C, "Transducers Direct, LLC");
        companies.put(0x010D, "Fujitsu Ten LImited");
        companies.put(0x010E, "Audi AG");
        companies.put(0x010F, "HiSilicon Technologies Col, Ltd.");
        companies.put(0x0110, "Nippon Seiki Co., Ltd.");
        companies.put(0x0111, "Steelseries ApS");
        companies.put(0x0112, "Visybl Inc.");
        companies.put(0x0113, "Openbrain Technologies, Co., Ltd.");
        companies.put(0x0114, "Xensr");
        companies.put(0x0115, "e.solutions");
        companies.put(0x0116, "10AK Technologies");
        companies.put(0x0117, "Wimoto Technologies Inc");
        companies.put(0x0118, "Radius Networks, Inc.");
        companies.put(0x0119, "Wize Technology Co., Ltd.");
        companies.put(0x011A, "Qualcomm Labs, Inc.");
        companies.put(0x011B, "Aruba Networks");
        companies.put(0x011C, "Baidu");
        companies.put(0x011D, "Arendi AG");
        companies.put(0x011E, "Skoda Auto a.s.");
        companies.put(0x011F, "Volkswagen AG");
        companies.put(0x0120, "Porsche AG");
        companies.put(0x0121, "Sino Wealth Electronic Ltd.");
        companies.put(0x0122, "AirTurn, Inc.");
        companies.put(0x0123, "Kinsa, Inc");
        companies.put(0x0124, "HID Global");
        companies.put(0x0125, "SEAT es");
        companies.put(0x0126, "Promethean Ltd.");
        companies.put(0x0127, "Salutica Allied Solutions");
        companies.put(0x0128, "GPSI Group Pty Ltd");
        companies.put(0x0129, "Nimble Devices Oy");
        companies.put(0x012A, "Changzhou Yongse Infotech Co., Ltd.");
        companies.put(0x012B, "SportIQ");
        companies.put(0x012C, "TEMEC Instruments B.V.");
        companies.put(0x012D, "Sony Corporation");
        companies.put(0x012E, "ASSA ABLOY");
        companies.put(0x012F, "Clarion Co. Inc.");
        companies.put(0x0130, "Warehouse Innovations");
        companies.put(0x0131, "Cypress Semiconductor");
        companies.put(0x0132, "MADS Inc");
        companies.put(0x0133, "Blue Maestro Limited");
        companies.put(0x0134, "Resolution Products, Ltd.");
        companies.put(0x0135, "Aireware LLC");
        companies.put(0x0136, "Silvair, Inc.");
        companies.put(0x0137, "Prestigio Plaza Ltd.");
        companies.put(0x0138, "NTEO Inc.");
        companies.put(0x0139, "Focus Systems Corporation");
        companies.put(0x013A, "Tencent Holdings Ltd.");
        companies.put(0x013B, "Allegion");
        companies.put(0x013C, "Murata Manufacturing Co., Ltd.");
        companies.put(0x013D, "WirelessWERX");
        companies.put(0x013E, "Nod, Inc.");
        companies.put(0x013F, "B&B Manufacturing Company");
        companies.put(0x0140, "Alpine Electronics (China) Co., Ltd");
        companies.put(0x0141, "FedEx Services");
        companies.put(0x0142, "Grape Systems Inc.");
        companies.put(0x0143, "Bkon Connect");
        companies.put(0x0144, "Lintech GmbH");
        companies.put(0x0145, "Novatel Wireless");
        companies.put(0x0146, "Ciright");
        companies.put(0x0147, "Mighty Cast, Inc.");
        companies.put(0x0148, "Ambimat Electronics");
        companies.put(0x0149, "Perytons Ltd.");
        companies.put(0x014A, "Tivoli Audio, LLC");
        companies.put(0x014B, "Master Lock");
        companies.put(0x014C, "Mesh-Net Ltd");
        companies.put(0x014D, "HUIZHOU DESAY SV AUTOMOTIVE CO., LTD.");
        companies.put(0x014E, "Tangerine, Inc.");
        companies.put(0x014F, "B&W Group Ltd.");
        companies.put(0x0150, "Pioneer Corporation");
        companies.put(0x0151, "OnBeep");
        companies.put(0x0152, "Vernier Software & Technology");
        companies.put(0x0153, "ROL Ergo");
        companies.put(0x0154, "Pebble Technology");
        companies.put(0x0155, "NETATMO");
        companies.put(0x0156, "Accumulate AB");
        companies.put(0x0157, "Anhui Huami Information Technology Co., Ltd.");
        companies.put(0x0158, "Inmite s.r.o.");
        companies.put(0x0159, "ChefSteps, Inc.");
        companies.put(0x015A, "micas AG");
        companies.put(0x015B, "Biomedical Research Ltd.");
        companies.put(0x015C, "Pitius Tec S.L.");
        companies.put(0x015D, "Estimote, Inc.");
        companies.put(0x015E, "Unikey Technologies, Inc.");
        companies.put(0x015F, "Timer Cap Co.");
        companies.put(0x0160, "AwoX");
        companies.put(0x0161, "yikes");
        companies.put(0x0162, "MADSGlobalNZ Ltd.");
        companies.put(0x0163, "PCH International");
        companies.put(0x0164, "Qingdao Yeelink Information Technology Co., Ltd.");
        companies.put(0x0165, "Milwaukee Tool (Formally Milwaukee Electric Tools)");
        companies.put(0x0166, "MISHIK Pte Ltd");
        companies.put(0x0167, "Bayer HealthCare");
        companies.put(0x0168, "Spicebox LLC");
        companies.put(0x0169, "emberlight");
        companies.put(0x016A, "Cooper-Atkins Corporation");
        companies.put(0x016B, "Qblinks");
        companies.put(0x016C, "MYSPHERA");
        companies.put(0x016D, "LifeScan Inc");
        companies.put(0x016E, "Volantic AB");
        companies.put(0x016F, "Podo Labs, Inc");
        companies.put(0x0170, "Roche Diabetes Care AG");
        companies.put(0x0171, "Amazon Fulfillment Service");
        companies.put(0x0172, "Connovate Technology Private Limited");
        companies.put(0x0173, "Kocomojo, LLC");
        companies.put(0x0174, "Everykey Inc.");
        companies.put(0x0175, "Dynamic Controls");
        companies.put(0x0176, "SentriLock");
        companies.put(0x0177, "I-SYST inc.");
        companies.put(0x0178, "CASIO COMPUTER CO., LTD.");
        companies.put(0x0179, "LAPIS Semiconductor Co., Ltd.");
        companies.put(0x017A, "Telemonitor, Inc.");
        companies.put(0x017B, "taskit GmbH");
        companies.put(0x017C, "Daimler AG");
        companies.put(0x017D, "BatAndCat");
        companies.put(0x017E, "BluDotz Ltd");
        companies.put(0x017F, "XTel Wireless ApS");
        companies.put(0x0180, "Gigaset Communications GmbH");
        companies.put(0x0181, "Gecko Health Innovations, Inc.");
        companies.put(0x0182, "HOP Ubiquitous");
        companies.put(0x0183, "Walt Disney");
        companies.put(0x0184, "Nectar");
        companies.put(0x0185, "bel'apps LLC");
        companies.put(0x0186, "CORE Lighting Ltd");
        companies.put(0x0187, "Seraphim Sense Ltd");
        companies.put(0x0188, "Unico RBC");
        companies.put(0x0189, "Physical Enterprises Inc.");
        companies.put(0x018A, "Able Trend Technology Limited");
        companies.put(0x018B, "Konica Minolta, Inc.");
        companies.put(0x018C, "Wilo SE");
        companies.put(0x018D, "Extron Design Services");
        companies.put(0x018E, "Fitbit, Inc.");
        companies.put(0x018F, "Fireflies Systems");
        companies.put(0x0190, "Intelletto Technologies Inc.");
        companies.put(0x0191, "FDK CORPORATION");
        companies.put(0x0192, "Cloudleaf, Inc");
        companies.put(0x0193, "Maveric Automation LLC");
        companies.put(0x0194, "Acoustic Stream Corporation");
        companies.put(0x0195, "Zuli");
        companies.put(0x0196, "Paxton Access Ltd");
        companies.put(0x0197, "WiSilica Inc.");
        companies.put(0x0198, "VENGIT Korlatolt Felelossegu Tarsasag");
        companies.put(0x0199, "SALTO SYSTEMS S.L.");
        companies.put(0x019A, "TRON Forum (formerly T-Engine Forum)");
        companies.put(0x019B, "CUBETECH s.r.o.");
        companies.put(0x019C, "Cokiya Incorporated");
        companies.put(0x019D, "CVS Health");
        companies.put(0x019E, "Ceruus");
        companies.put(0x019F, "Strainstall Ltd");
        companies.put(0x01A0, "Channel Enterprises (HK) Ltd.");
        companies.put(0x01A1, "FIAMM");
        companies.put(0x01A2, "GIGALANE.CO.,LTD");
        companies.put(0x01A3, "EROAD");
        companies.put(0x01A4, "Mine Safety Appliances");
        companies.put(0x01A5, "Icon Health and Fitness");
        companies.put(0x01A6, "Asandoo GmbH");
        companies.put(0x01A7, "ENERGOUS CORPORATION");
        companies.put(0x01A8, "Taobao");
        companies.put(0x01A9, "Canon Inc.");
        companies.put(0x01AA, "Geophysical Technology Inc.");
        companies.put(0x01AB, "Facebook, Inc.");
        companies.put(0x01AC, "Nipro Diagnostics, Inc.");
        companies.put(0x01AD, "FlightSafety International");
        companies.put(0x01AE, "Earlens Corporation");
        companies.put(0x01AF, "Sunrise Micro Devices, Inc.");
        companies.put(0x01B0, "Star Micronics Co., Ltd.");
        companies.put(0x01B1, "Netizens Sp. z o.o.");
        companies.put(0x01B2, "Nymi Inc.");
        companies.put(0x01B3, "Nytec, Inc.");
        companies.put(0x01B4, "Trineo Sp. z o.o.");
        companies.put(0x01B5, "Nest Labs Inc.");
        companies.put(0x01B6, "LM Technologies Ltd");
        companies.put(0x01B7, "General Electric Company");
        companies.put(0x01B8, "i+D3 S.L.");
        companies.put(0x01B9, "HANA Micron");
        companies.put(0x01BA, "Stages Cycling LLC");
        companies.put(0x01BB, "Cochlear Bone Anchored Solutions AB");
        companies.put(0x01BC, "SenionLab AB");
        companies.put(0x01BD, "Syszone Co., Ltd");
        companies.put(0x01BE, "Pulsate Mobile Ltd.");
        companies.put(0x01BF, "Hong Kong HunterSun Electronic Limited");
        companies.put(0x01C0, "pironex GmbH");
        companies.put(0x01C1, "BRADATECH Corp.");
        companies.put(0x01C2, "Transenergooil AG");
        companies.put(0x01C3, "Bunch");
        companies.put(0x01C4, "DME Microelectronics");
        companies.put(0x01C5, "Bitcraze AB");
        companies.put(0x01C6, "HASWARE Inc.");
        companies.put(0x01C7, "Abiogenix Inc.");
        companies.put(0x01C8, "Poly-Control ApS");
        companies.put(0x01C9, "Avi-on");
        companies.put(0x01CA, "Laerdal Medical AS");
        companies.put(0x01CB, "Fetch My Pet");
        companies.put(0x01CC, "Sam Labs Ltd.");
        companies.put(0x01CD, "Chengdu Synwing Technology Ltd");
        companies.put(0x01CE, "HOUWA SYSTEM DESIGN, k.k.");
        companies.put(0x01CF, "BSH");
        companies.put(0x01D0, "Primus Inter Pares Ltd");
        companies.put(0x01D1, "August Home, Inc");
        companies.put(0x01D2, "Gill Electronics");
        companies.put(0x01D3, "Sky Wave Design");
        companies.put(0x01D4, "Newlab S.r.l.");
        companies.put(0x01D5, "ELAD srl");
        companies.put(0x01D6, "G-wearables inc.");
        companies.put(0x01D7, "Squadrone Systems Inc.");
        companies.put(0x01D8, "Code Corporation");
        companies.put(0x01D9, "Savant Systems LLC");
        companies.put(0x01DA, "Logitech International SA");
        companies.put(0x01DB, "Innblue Consulting");
        companies.put(0x01DC, "iParking Ltd.");
        companies.put(0x01DD, "Koninklijke Philips Electronics N.V.");
        companies.put(0x01DE, "Minelab Electronics Pty Limited");
        companies.put(0x01DF, "Bison Group Ltd.");
        companies.put(0x01E0, "Widex A/S");
        companies.put(0x01E1, "Jolla Ltd");
        companies.put(0x01E2, "Lectronix, Inc.");
        companies.put(0x01E3, "Caterpillar Inc");
        companies.put(0x01E4, "Freedom Innovations");
        companies.put(0x01E5, "Dynamic Devices Ltd");
        companies.put(0x01E6, "Technology Solutions (UK) Ltd");
        companies.put(0x01E7, "IPS Group Inc.");
        companies.put(0x01E8, "STIR");
        companies.put(0x01E9, "Sano, Inc.");
        companies.put(0x01EA, "Advanced Application Design, Inc.");
        companies.put(0x01EB, "AutoMap LLC");
        companies.put(0x01EC, "Spreadtrum Communications Shanghai Ltd");
        companies.put(0x01ED, "CuteCircuit LTD");
        companies.put(0x01EE, "Valeo Service");
        companies.put(0x01EF, "Fullpower Technologies, Inc.");
        companies.put(0x01F0, "KloudNation");
        companies.put(0x01F1, "Zebra Technologies Corporation");
        companies.put(0x01F2, "Itron, Inc.");
        companies.put(0x01F3, "The University of Tokyo");
        companies.put(0x01F4, "UTC Fire and Security");
        companies.put(0x01F5, "Cool Webthings Limited");
        companies.put(0x01F6, "DJO Global");
        companies.put(0x01F7, "Gelliner Limited");
        companies.put(0x01F8, "Anyka (Guangzhou) Microelectronics Technology Co, LTD");
        companies.put(0x01F9, "Medtronic Inc.");
        companies.put(0x01FA, "Gozio Inc.");
        companies.put(0x01FB, "Form Lifting, LLC");
        companies.put(0x01FC, "Wahoo Fitness, LLC");
        companies.put(0x01FD, "Kontakt Micro-Location Sp. z o.o.");
        companies.put(0x01FE, "Radio Systems Corporation");
        companies.put(0x01FF, "Freescale Semiconductor, Inc.");
        companies.put(0x0200, "Verifone Systems Pte Ltd. Taiwan Branch");
        companies.put(0x0201, "AR Timing");
        companies.put(0x0202, "Rigado LLC");
        companies.put(0x0203, "Kemppi Oy");
        companies.put(0x0204, "Tapcentive Inc.");
        companies.put(0x0205, "Smartbotics Inc.");
        companies.put(0x0206, "Otter Products, LLC");
        companies.put(0x0207, "STEMP Inc.");
        companies.put(0x0208, "LumiGeek LLC");
        companies.put(0x0209, "InvisionHeart Inc.");
        companies.put(0x020A, "Macnica Inc.");
        companies.put(0x020B, "Jaguar Land Rover Limited");
        companies.put(0x020C, "CoroWare Technologies, Inc");
        companies.put(0x020D, "Simplo Technology Co., LTD");
        companies.put(0x020E, "Omron Healthcare Co., LTD");
        companies.put(0x020F, "Comodule GMBH");
        companies.put(0x0210, "ikeGPS");
        companies.put(0x0211, "Telink Semiconductor Co. Ltd");
        companies.put(0x0212, "Interplan Co., Ltd");
        companies.put(0x0213, "Wyler AG");
        companies.put(0x0214, "IK Multimedia Production srl");
        companies.put(0x0215, "Lukoton Experience Oy");
        companies.put(0x0216, "MTI Ltd");
        companies.put(0x0217, "Tech4home, Lda");
        companies.put(0x0218, "Hiotech AB");
        companies.put(0x0219, "DOTT Limited");
        companies.put(0x021A, "Blue Speck Labs, LLC");
        companies.put(0x021B, "Cisco Systems, Inc");
        companies.put(0x021C, "Mobicomm Inc");
        companies.put(0x021D, "Edamic");
        companies.put(0x021E, "Goodnet, Ltd");
        companies.put(0x021F, "Luster Leaf Products Inc");
        companies.put(0x0220, "Manus Machina BV");
        companies.put(0x0221, "Mobiquity Networks Inc");
        companies.put(0x0222, "Praxis Dynamics");
        companies.put(0x0223, "Philip Morris Products S.A.");
        companies.put(0x0224, "Comarch SA");
        companies.put(0x0225, "Nestl Nespresso S.A.");
        companies.put(0x0226, "Merlinia A/S");
        companies.put(0x0227, "LifeBEAM Technologies");
        companies.put(0x0228, "Twocanoes Labs, LLC");
        companies.put(0x0229, "Muoverti Limited");
        companies.put(0x022A, "Stamer Musikanlagen GMBH");
        companies.put(0x022B, "Tesla Motors");
        companies.put(0x022C, "Pharynks Corporation");
        companies.put(0x022D, "Lupine");
        companies.put(0x022E, "Siemens AG");
        companies.put(0x022F, "Huami (Shanghai) Culture Communication CO., LTD");
        companies.put(0x0230, "Foster Electric Company, Ltd");
        companies.put(0x0231, "ETA SA");
        companies.put(0x0232, "x-Senso Solutions Kft");
        companies.put(0x0233, "Shenzhen SuLong Communication Ltd");
        companies.put(0x0234, "FengFan (BeiJing) Technology Co, Ltd");
        companies.put(0x0235, "Qrio Inc");
        companies.put(0x0236, "Pitpatpet Ltd");
        companies.put(0x0237, "MSHeli s.r.l.");
        companies.put(0x0238, "Trakm8 Ltd");
        companies.put(0x0239, "JIN CO, Ltd");
        companies.put(0x023A, "Alatech Tehnology");
        companies.put(0x023B, "Beijing CarePulse Electronic Technology Co, Ltd");
        companies.put(0x023C, "Awarepoint");
        companies.put(0x023D, "ViCentra B.V.");
        companies.put(0x023E, "Raven Industries");
        companies.put(0x023F, "WaveWare Technologies Inc.");
        companies.put(0x0240, "Argenox Technologies");
        companies.put(0x0241, "Bragi GmbH");
        companies.put(0x0242, "16Lab Inc");
        companies.put(0x0243, "Masimo Corp");
        companies.put(0x0244, "Iotera Inc");
        companies.put(0x0245, "Endress+Hauser");
        companies.put(0x0246, "ACKme Networks, Inc.");
        companies.put(0x0247, "FiftyThree Inc.");
        companies.put(0x0248, "Parker Hannifin Corp");
        companies.put(0x0249, "Transcranial Ltd");
        companies.put(0x024A, "Uwatec AG");
        companies.put(0x024B, "Orlan LLC");
        companies.put(0x024C, "Blue Clover Devices");
        companies.put(0x024D, "M-Way Solutions GmbH");
        companies.put(0x024E, "Microtronics Engineering GmbH");
        companies.put(0x024F, "Schneider Schreibgerte GmbH");
        companies.put(0x0250, "Sapphire Circuits LLC");
        companies.put(0x0251, "Lumo Bodytech Inc.");
        companies.put(0x0252, "UKC Technosolution");
        companies.put(0x0253, "Xicato Inc.");
        companies.put(0x0254, "Playbrush");
        companies.put(0x0255, "Dai Nippon Printing Co., Ltd.");
        companies.put(0x0256, "G24 Power Limited");
        companies.put(0x0257, "AdBabble Local Commerce Inc.");
        companies.put(0x0258, "Devialet SA");
        companies.put(0x0259, "ALTYOR");
        companies.put(0x025A, "University of Applied Sciences Valais/Haute Ecole Valaisanne");
        companies.put(0x025B, "Five Interactive, LLC dba Zendo");
        companies.put(0x025C, "NetEaseHangzhouNetwork co.Ltd.");
        companies.put(0x025D, "Lexmark International Inc.");
        companies.put(0x025E, "Fluke Corporation");
        companies.put(0x025F, "Yardarm Technologies");
        companies.put(0x0260, "SensaRx");
        companies.put(0x0261, "SECVRE GmbH");
        companies.put(0x0262, "Glacial Ridge Technologies");
        companies.put(0x0263, "Identiv, Inc.");
        companies.put(0x0264, "DDS, Inc.");
        companies.put(0x0265, "SMK Corporation");
        companies.put(0x0266, "Schawbel Technologies LLC");
        companies.put(0x0267, "XMI Systems SA");
        companies.put(0x0268, "Cerevo");
        companies.put(0x0269, "Torrox GmbH & Co KG");
        companies.put(0x026A, "Gemalto");
        companies.put(0x026B, "DEKA Research & Development Corp.");
        companies.put(0x026C, "Domster Tadeusz Szydlowski");
        companies.put(0x026D, "Technogym SPA");
        companies.put(0x026E, "FLEURBAEY BVBA");
        companies.put(0x026F, "Aptcode Solutions");
        companies.put(0x0270, "LSI ADL Technology");
        companies.put(0x0271, "Animas Corp");
        companies.put(0x0272, "Alps Electric Co., Ltd.");
        companies.put(0x0273, "OCEASOFT");
        companies.put(0x0274, "Motsai Research");
        companies.put(0x0275, "Geotab");
        companies.put(0x0276, "E.G.O. Elektro-Gertebau GmbH");
        companies.put(0x0277, "bewhere inc");
        companies.put(0x0278, "Johnson Outdoors Inc");
        companies.put(0x0279, "steute Schaltgerate GmbH & Co. KG");
        companies.put(0x027A, "Ekomini inc.");
        companies.put(0x027B, "DEFA AS");
        companies.put(0x027C, "Aseptika Ltd");
        companies.put(0x027D, "HUAWEI Technologies Co., Ltd. ( )");
        companies.put(0x027E, "HabitAware, LLC");
        companies.put(0x027F, "ruwido austria gmbh");
        companies.put(0x0280, "ITEC corporation");
        companies.put(0x0281, "StoneL");
        companies.put(0x0282, "Sonova AG");
        companies.put(0x0283, "Maven Machines, Inc.");
        companies.put(0x0284, "Synapse Electronics");
        companies.put(0x0285, "Standard Innovation Inc.");
        companies.put(0x0286, "RF Code, Inc.");
        companies.put(0x0287, "Wally Ventures S.L.");
        companies.put(0x0288, "Willowbank Electronics Ltd");
        companies.put(0x0289, "SK Telecom");
        companies.put(0x028A, "Jetro AS");
        companies.put(0x028B, "Code Gears LTD");
        companies.put(0x028C, "NANOLINK APS");
        companies.put(0x028D, "IF, LLC");
        companies.put(0x028E, "RF Digital Corp");
        companies.put(0x028F, "Church & Dwight Co., Inc");
        companies.put(0x0290, "Multibit Oy");
        companies.put(0x0291, "CliniCloud Inc");
        companies.put(0x0292, "SwiftSensors");
        companies.put(0x0293, "Blue Bite");
        companies.put(0x0294, "ELIAS GmbH");
        companies.put(0x0295, "Sivantos GmbH");
        companies.put(0x0296, "Petzl");
        companies.put(0x0297, "storm power ltd");
        companies.put(0x0298, "EISST Ltd");
        companies.put(0x0299, "Inexess Technology Simma KG");
        companies.put(0x029A, "Currant, Inc.");
        companies.put(0x029B, "C2 Development, Inc.");
        companies.put(0x029C, "Blue Sky Scientific, LLC");
        companies.put(0x029D, "ALOTTAZS LABS, LLC");
        companies.put(0x029E, "Kupson spol. s r.o.");
        companies.put(0x029F, "Areus Engineering GmbH");
        companies.put(0x02A0, "Impossible Camera GmbH");
        companies.put(0x02A1, "InventureTrack Systems");
        companies.put(0x02A2, "LockedUp");
        companies.put(0x02A3, "Itude");
        companies.put(0x02A4, "Pacific Lock Company");
        companies.put(0x02A5, "Tendyron Corporation ( )");
        companies.put(0x02A6, "Robert Bosch GmbH");
        companies.put(0x02A7, "Illuxtron international B.V.");
        companies.put(0x02A8, "miSport Ltd.");
        companies.put(0x02A9, "Chargelib");
        companies.put(0x02AA, "Doppler Lab");
        companies.put(0x02AB, "BBPOS Limited");
        companies.put(0x02AC, "RTB Elektronik GmbH & Co. KG");
        companies.put(0x02AD, "Rx Networks, Inc.");
        companies.put(0x02AE, "WeatherFlow, Inc.");
        companies.put(0x02AF, "Technicolor USA Inc.");
        companies.put(0x02B0, "Bestechnic(Shanghai),Ltd");
        companies.put(0x02B1, "Raden Inc");
        companies.put(0x02B2, "JouZen Oy");
        companies.put(0x02B3, "CLABER S.P.A.");
        companies.put(0x02B4, "Hyginex, Inc.");
        companies.put(0x02B5, "HANSHIN ELECTRIC RAILWAY CO.,LTD.");
        companies.put(0x02B6, "Schneider Electric");
        companies.put(0x02B7, "Oort Technologies LLC");
        companies.put(0x02B8, "Chrono Therapeutics");
        companies.put(0x02B9, "Rinnai Corporation");
        companies.put(0x02BA, "Swissprime Technologies AG");
        companies.put(0x02BB, "Koha.,Co.Ltd");
        companies.put(0x02BC, "Genevac Ltd");
        companies.put(0x02BD, "Chemtronics");
        companies.put(0x02BE, "Seguro Technology Sp. z o.o.");
        companies.put(0x02BF, "Redbird Flight Simulations");
        companies.put(0x02C0, "Dash Robotics");
        companies.put(0x02C1, "LINE Corporation");
        companies.put(0x02C2, "Guillemot Corporation");
        companies.put(0x02C3, "Techtronic Power Tools Technology Limited");
        companies.put(0x02C4, "Wilson Sporting Goods");
        companies.put(0x02C5, "Lenovo (Singapore) Pte Ltd. ( )");
        companies.put(0x02C6, "Ayatan Sensors");
        companies.put(0x02C7, "Electronics Tomorrow Limited");
        companies.put(0x02C8, "VASCO Data Security International, Inc.");
        companies.put(0x02C9, "PayRange Inc.");
        companies.put(0x02CA, "ABOV Semiconductor");
        companies.put(0x02CB, "AINA-Wireless Inc.");
        companies.put(0x02CC, "Eijkelkamp Soil & Water");
        companies.put(0x02CD, "BMA ergonomics b.v.");
        companies.put(0x02CE, "Teva Branded Pharmaceutical Products R&D, Inc.");
        companies.put(0x02CF, "Anima");
        companies.put(0x02D0, "3M");
        companies.put(0x02D1, "Empatica Srl");
        companies.put(0x02D2, "Afero, Inc.");
        companies.put(0x02D3, "Powercast Corporation");
        companies.put(0x02D4, "Secuyou ApS");
        companies.put(0x02D5, "OMRON Corporation");
        companies.put(0x02D6, "Send Solutions");
        companies.put(0x02D7, "NIPPON SYSTEMWARE CO.,LTD.");
        companies.put(0x02D8, "Neosfar");
        companies.put(0x02D9, "Fliegl Agrartechnik GmbH");
        companies.put(0x02DA, "Gilvader");
        companies.put(0x02DB, "Digi International Inc (R)");
        companies.put(0x02DC, "DeWalch Technologies, Inc.");
        companies.put(0x02DD, "Flint Rehabilitation Devices, LLC");
        companies.put(0x02DE, "Samsung SDS Co., Ltd.");
        companies.put(0x02DF, "Blur Product Development");
        companies.put(0x02E0, "University of Michigan");
        companies.put(0x02E1, "Victron Energy BV");
        companies.put(0x02E2, "NTT docomo");
        companies.put(0x02E3, "Carmanah Technologies Corp.");
        companies.put(0x02E4, "Bytestorm Ltd.");
        companies.put(0x02E5, "Espressif Incorporated ( () )");
        companies.put(0x02E6, "Unwire");
        companies.put(0x02E7, "Connected Yard, Inc.");
        companies.put(0x02E8, "American Music Environments");
        companies.put(0x02E9, "Sensogram Technologies, Inc.");
        companies.put(0x02EA, "Fujitsu Limited");
        companies.put(0x02EB, "Ardic Technology");
        companies.put(0x02EC, "Delta Systems, Inc");
        companies.put(0x02ED, "HTC Corporation");
        companies.put(0x02EE, "Citizen Holdings Co., Ltd.");
        companies.put(0x02EF, "SMART-INNOVATION.inc");
        companies.put(0x02F0, "Blackrat Software");
        companies.put(0x02F1, "The Idea Cave, LLC");
        companies.put(0x02F2, "GoPro, Inc.");
        companies.put(0x02F3, "AuthAir, Inc");
        companies.put(0x02F4, "Vensi, Inc.");
        companies.put(0x02F5, "Indagem Tech LLC");
        companies.put(0x02F6, "Intemo Technologies");
        companies.put(0x02F7, "DreamVisions co., Ltd.");
        companies.put(0x02F8, "Runteq Oy Ltd");
        companies.put(0x02F9, "IMAGINATION TECHNOLOGIES LTD");
        companies.put(0x02FA, "CoSTAR TEchnologies");
        companies.put(0x02FB, "Clarius Mobile Health Corp.");
        companies.put(0x02FC, "Shanghai Frequen Microelectronics Co., Ltd.");
        companies.put(0x02FD, "Uwanna, Inc.");
        companies.put(0x02FE, "Lierda Science & Technology Group Co., Ltd.");
        companies.put(0x02FF, "Silicon Laboratories");
        companies.put(0x0300, "World Moto Inc.");
        companies.put(0x0301, "Giatec Scientific Inc.");
        companies.put(0x0302, "Loop Devices, Inc");
        companies.put(0x0303, "IACA electronique");
        companies.put(0x0304, "Martians Inc");
        companies.put(0x0305, "Swipp ApS");
        companies.put(0x0306, "Life Laboratory Inc.");
        companies.put(0x0307, "FUJI INDUSTRIAL CO.,LTD.");
        companies.put(0x0308, "Surefire, LLC");
        companies.put(0x0309, "Dolby Labs");
        companies.put(0x030A, "Ellisys");
        companies.put(0x030B, "Magnitude Lighting Converters");
        companies.put(0x030C, "Hilti AG");
        companies.put(0x030D, "Devdata S.r.l.");
        companies.put(0x030E, "Deviceworx");
        companies.put(0x030F, "Shortcut Labs");
        companies.put(0x0310, "SGL Italia S.r.l.");
        companies.put(0x0311, "PEEQ DATA");
        companies.put(0x0312, "Ducere Technologies Pvt Ltd");
        companies.put(0x0313, "DiveNav, Inc.");
        companies.put(0x0314, "RIIG AI Sp. z o.o.");
        companies.put(0x0315, "Thermo Fisher Scientific");
        companies.put(0x0316, "AG Measurematics Pvt. Ltd.");
        companies.put(0x0317, "CHUO Electronics CO., LTD.");
        companies.put(0x0318, "Aspenta International");
        companies.put(0x0319, "Eugster Frismag AG");
        companies.put(0x031A, "Amber wireless GmbH");
        companies.put(0x031B, "HQ Inc");
        companies.put(0x031C, "Lab Sensor Solutions");
        companies.put(0x031D, "Enterlab ApS");
        companies.put(0x031E, "Eyefi, Inc.");
        companies.put(0x031F, "MetaSystem S.p.A.");
        companies.put(0x0320, "SONO ELECTRONICS. CO., LTD");
        companies.put(0x0321, "Jewelbots");
        companies.put(0x0322, "Compumedics Limited");
        companies.put(0x0323, "Rotor Bike Components");
        companies.put(0x0324, "Astro, Inc.");
        companies.put(0x0325, "Amotus Solutions");
        companies.put(0x0326, "Healthwear Technologies (Changzhou)Ltd");
        companies.put(0x0327, "Essex Electronics");
        companies.put(0x0328, "Grundfos A/S");
        companies.put(0x0329, "Eargo, Inc.");
        companies.put(0x032A, "Electronic Design Lab");
        companies.put(0x032B, "ESYLUX");
        companies.put(0x032C, "NIPPON SMT.CO.,Ltd");
        companies.put(0x032D, "BM innovations GmbH");
        companies.put(0x032E, "indoormap");
        companies.put(0x032F, "OttoQ Inc");
        companies.put(0x0330, "North Pole Engineering");
        companies.put(0x0331, "3flares Technologies Inc.");
        companies.put(0x0332, "Electrocompaniet A.S.");
        companies.put(0x0333, "Mul-T-Lock");
        companies.put(0x0334, "Corentium AS");
        companies.put(0x0335, "Enlighted Inc");
        companies.put(0x0336, "GISTIC");
        companies.put(0x0337, "AJP2 Holdings, LLC");
        companies.put(0x0338, "COBI GmbH");
        companies.put(0x0339, "Blue Sky Scientific, LLC");
        companies.put(0x033A, "Appception, Inc.");
        companies.put(0x033B, "Courtney Thorne Limited");
        companies.put(0x033C, "Virtuosys");
        companies.put(0x033D, "TPV Technology Limited");
        companies.put(0x033E, "Monitra SA");
        companies.put(0x033F, "Automation Components, Inc.");
        companies.put(0x0340, "Letsense s.r.l.");
        companies.put(0x0341, "Etesian Technologies LLC");
        companies.put(0x0342, "GERTEC BRASIL LTDA.");
        companies.put(0x0343, "Drekker Development Pty. Ltd.");
        companies.put(0x0344, "Whirl Inc");
        companies.put(0x0345, "Locus Positioning");
        companies.put(0x0346, "Acuity Brands Lighting, Inc");
        companies.put(0x0347, "Prevent Biometrics");
        companies.put(0x0348, "Arioneo");
        companies.put(0x0349, "VersaMe");
        companies.put(0x034A, "Vaddio");
        companies.put(0x034B, "Libratone A/S");
        companies.put(0x034C, "HM Electronics, Inc.");
        companies.put(0x034D, "TASER International, Inc.");
        companies.put(0x034E, "SafeTrust Inc.");
        companies.put(0x034F, "Heartland Payment Systems");
        companies.put(0x0350, "Bitstrata Systems Inc.");
        companies.put(0x0351, "Pieps GmbH");
        companies.put(0x0352, "iRiding(Xiamen)Technology Co.,Ltd.");
        companies.put(0x0353, "Alpha Audiotronics, Inc.");
        companies.put(0x0354, "TOPPAN FORMS CO.,LTD.");
        companies.put(0x0355, "Sigma Designs, Inc.");
        companies.put(0x0356, "Spectrum Brands, Inc.");
        companies.put(0x0357, "Polymap Wireless");
        companies.put(0x0358, "MagniWare Ltd.");
        companies.put(0x0359, "Novotec Medical GmbH");
        companies.put(0x035A, "Medicom Innovation Partner a/s");
        companies.put(0x035B, "Matrix Inc.");
        companies.put(0x035C, "Eaton Corporation");
        companies.put(0x035D, "KYS");
        companies.put(0x035E, "Naya Health, Inc.");
        companies.put(0x035F, "Acromag");
        companies.put(0x0360, "Insulet Corporation");
        companies.put(0x0361, "Wellinks Inc.");
        companies.put(0x0362, "ON Semiconductor");
        companies.put(0x0363, "FREELAP SA");
        companies.put(0x0364, "Favero Electronics Srl");
        companies.put(0x0365, "BioMech Sensor LLC");
        companies.put(0x0366, "BOLTT Sports technologies Private limited");
        companies.put(0x0367, "Saphe International");
        companies.put(0x0368, "Metormote AB");
        companies.put(0x0369, "littleBits");
        companies.put(0x036A, "SetPoint Medical");
        companies.put(0x036B, "BRControls Products BV");
        companies.put(0x036C, "Zipcar");
        companies.put(0x036D, "AirBolt Pty Ltd");
        companies.put(0x036E, "KeepTruckin Inc");
        companies.put(0x036F, "Motiv, Inc.");
        companies.put(0x0370, "Wazombi Labs O");
        companies.put(0x0371, "ORBCOMM");
        companies.put(0x0372, "Nixie Labs, Inc.");
        companies.put(0x0373, "AppNearMe Ltd");
        companies.put(0x0374, "Holman Industries");
        companies.put(0x0375, "Expain AS");
        companies.put(0x0376, "Electronic Temperature Instruments Ltd");
        companies.put(0x0377, "Plejd AB");
        companies.put(0x0378, "Propeller Health");
        companies.put(0x0379, "Shenzhen iMCO Electronic Technology Co.,Ltd");
        companies.put(0x037A, "Algoria");
        companies.put(0x037B, "Apption Labs Inc.");
        companies.put(0x037C, "Cronologics Corporation");
        companies.put(0x037D, "MICRODIA Ltd.");
        companies.put(0x037E, "lulabytes S.L.");
        companies.put(0x037F, "Nestec S.A.");
        companies.put(0x0380, "LLC MEGA-F service");
        companies.put(0x0381, "Sharp Corporation");
        companies.put(0x0382, "Precision Outcomes Ltd");
        companies.put(0x0383, "Kronos Incorporated");
        companies.put(0x0384, "OCOSMOS Co., Ltd.");
        companies.put(0x0385, "Embedded Electronic Solutions Ltd. dba e2Solutions");
        companies.put(0x0386, "Aterica Inc.");
        companies.put(0x0387, "BluStor PMC, Inc.");
        companies.put(0x0388, "Kapsch TrafficCom AB");
        companies.put(0x0389, "ActiveBlu Corporation");
        companies.put(0x038A, "Kohler Mira Limited");
        companies.put(0x038B, "Noke");
        companies.put(0x038C, "Appion Inc.");
        companies.put(0x038D, "Resmed Ltd");
        companies.put(0x038E, "Crownstone B.V.");
        companies.put(0x038F, "Xiaomi Inc.");
        companies.put(0x0390, "INFOTECH s.r.o.");
        companies.put(0x0391, "Thingsquare AB");
        companies.put(0x0392, "T&D");
        companies.put(0x0393, "LAVAZZA S.p.A.");
        companies.put(0x0394, "Netclearance Systems, Inc.");
        companies.put(0x0395, "SDATAWAY");
        companies.put(0x0396, "BLOKS GmbH");
        companies.put(0x0397, "LEGO System A/S");
        companies.put(0x0398, "Thetatronics Ltd");
        companies.put(0x0399, "Nikon Corporation");
        companies.put(0x039A, "NeST");
        companies.put(0x039B, "South Silicon Valley Microelectronics");
        companies.put(0x039C, "ALE International");
        companies.put(0x039D, "CareView Communications, Inc.");
        companies.put(0x039E, "SchoolBoard Limited");
        companies.put(0x039F, "Molex Corporation");
        companies.put(0x03A0, "IVT Wireless Limited");
        companies.put(0x03A1, "Alpine Labs LLC");
        companies.put(0x03A2, "Candura Instruments");
        companies.put(0x03A3, "SmartMovt Technology Co., Ltd");
        companies.put(0x03A4, "Token Zero Ltd");
        companies.put(0x03A5, "ACE CAD Enterprise Co., Ltd. (ACECAD)");
        companies.put(0x03A6, "Medela, Inc");
        companies.put(0x03A7, "AeroScout");
        companies.put(0x03A8, "Esrille Inc.");
        companies.put(0x03A9, "THINKERLY SRL");
        companies.put(0x03AA, "Exon Sp. z o.o.");
        companies.put(0x03AB, "Meizu Technology Co., Ltd.");
        companies.put(0x03AC, "Smablo LTD");
        companies.put(0x03AD, "XiQ");
        companies.put(0x03AE, "Allswell Inc.");
        companies.put(0x03AF, "Comm-N-Sense Corp DBA Verigo");
        companies.put(0x03B0, "VIBRADORM GmbH");
        companies.put(0x03B1, "Otodata Wireless Network Inc.");
        companies.put(0x03B2, "Propagation Systems Limited");
        companies.put(0x03B3, "Midwest Instruments & Controls");
        companies.put(0x03B4, "Alpha Nodus, inc.");
        companies.put(0x03B5, "petPOMM, Inc");
        companies.put(0x03B6, "Mattel");
        companies.put(0x03B7, "Airbly Inc.");
        companies.put(0x03B8, "A-Safe Limited");
        companies.put(0x03B9, "FREDERIQUE CONSTANT SA");
        companies.put(0x03BA, "Maxscend Microelectronics Company Limited");
        companies.put(0x03BB, "Abbott Diabetes Care");
        companies.put(0x03BC, "ASB Bank Ltd");
        companies.put(0x03BD, "amadas");
        companies.put(0x03BE, "Applied Science, Inc.");
        companies.put(0x03BF, "iLumi Solutions Inc.");
        companies.put(0x03C0, "Arch Systems Inc.");
        companies.put(0x03C1, "Ember Technologies, Inc.");
        companies.put(0x03C2, "Snapchat Inc");
        companies.put(0x03C3, "Casambi Technologies Oy");
        companies.put(0x03C4, "Pico Technology Inc.");
        companies.put(0x03C5, "St. Jude Medical, Inc.");
        companies.put(0x03C6, "Intricon");
        companies.put(0x03C7, "Structural Health Systems, Inc.");
        companies.put(0x03C8, "Avvel International");
        companies.put(0x03C9, "Gallagher Group");
        companies.put(0x03CA, "In2things Automation Pvt. Ltd.");
        companies.put(0x03CB, "SYSDEV Srl");
        companies.put(0x03CC, "Vonkil Technologies Ltd");
        companies.put(0x03CD, "Wynd Technologies, Inc.");
        companies.put(0x03CE, "CONTRINEX S.A.");
        companies.put(0x03CF, "MIRA, Inc.");
        companies.put(0x03D0, "Watteam Ltd");
        companies.put(0x03D1, "Density Inc.");
        companies.put(0x03D2, "IOT Pot India Private Limited");
        companies.put(0x03D3, "Sigma Connectivity AB");
        companies.put(0x03D4, "PEG PEREGO SPA");
        companies.put(0x03D5, "Wyzelink Systems Inc.");
        companies.put(0x03D6, "Yota Devices LTD");
        companies.put(0x03D7, "FINSECUR");
        companies.put(0x03D8, "Zen-Me Labs Ltd");
        companies.put(0x03D9, "3IWare Co., Ltd.");
        companies.put(0x03DA, "EnOcean GmbH");
        companies.put(0x03DB, "Instabeat, Inc");
        companies.put(0x03DC, "Nima Labs");
        companies.put(0x03DD, "Andreas Stihl AG & Co. KG");
        companies.put(0x03DE, "Nathan Rhoades LLC");
        companies.put(0x03DF, "Grob Technologies, LLC");
        companies.put(0x03E0, "Actions (Zhuhai) Technology Co., Limited");
        companies.put(0x03E1, "SPD Development Company Ltd");
        companies.put(0x03E2, "Sensoan Oy");
        companies.put(0x03E3, "Qualcomm Life Inc");
        companies.put(0x03E4, "Chip-ing AG");
        companies.put(0x03E5, "ffly4u");
        companies.put(0x03E6, "IoT Instruments Oy");
        companies.put(0x03E7, "TRUE Fitness Technology");
        companies.put(0x03E8, "Reiner Kartengeraete GmbH & Co. KG.");
        companies.put(0x03E9, "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD.");
        companies.put(0x03EA, "Hello Inc.");
        companies.put(0x03EB, "Evollve Inc.");
        companies.put(0x03EC, "Jigowatts Inc.");
        companies.put(0x03ED, "BASIC MICRO.COM,INC.");
        companies.put(0x03EE, "CUBE TECHNOLOGIES");
        companies.put(0x03EF, "foolography GmbH");
        companies.put(0x03F0, "CLINK");
        companies.put(0x03F1, "Hestan Smart Cooking Inc.");
        companies.put(0x03F2, "WindowMaster A/S");
        companies.put(0x03F3, "Flowscape AB");
        companies.put(0x03F4, "PAL Technologies Ltd");
        companies.put(0x03F5, "WHERE, Inc.");
        companies.put(0x03F6, "Iton Technology Corp.");
        companies.put(0x03F7, "Owl Labs Inc.");
        companies.put(0x03F8, "Rockford Corp.");
        companies.put(0x03F9, "Becon Technologies Co.,Ltd.");
        companies.put(0x03FA, "Vyassoft Technologies Inc");
        companies.put(0x03FB, "Nox Medical");
        companies.put(0x03FC, "Kimberly-Clark");
        companies.put(0x03FD, "Trimble Navigation Ltd.");
        companies.put(0x03FE, "Littelfuse");
        companies.put(0x03FF, "Withings");
        companies.put(0x0400, "i-developer IT Beratung UG");
        companies.put(0x0401, "");
        companies.put(0x0402, "Sears Holdings Corporation");
        companies.put(0x0403, "Gantner Electronic GmbH");
        companies.put(0x0404, "Authomate Inc");
        companies.put(0x0405, "Vertex International, Inc.");
        companies.put(0x0406, "Airtago");
        companies.put(0x0407, "Swiss Audio SA");
        companies.put(0x0408, "ToGetHome Inc.");
        companies.put(0x0409, "AXIS");
        companies.put(0x040A, "Openmatics");
        companies.put(0x040B, "Jana Care Inc.");
        companies.put(0x040C, "Senix Corporation");
        companies.put(0x040D, "NorthStar Battery Company, LLC");
        companies.put(0x040E, "SKF (U.K.) Limited");
        companies.put(0x040F, "CO-AX Technology, Inc.");
        companies.put(0x0410, "Fender Musical Instruments");
        companies.put(0x0411, "Luidia Inc");
        companies.put(0x0412, "SEFAM");
        companies.put(0x0413, "Wireless Cables Inc");
        companies.put(0x0414, "Lightning Protection International Pty Ltd");
        companies.put(0x0415, "Uber Technologies Inc");
        companies.put(0x0416, "SODA GmbH");
        companies.put(0x0417, "Fatigue Science");
        companies.put(0x0418, "Alpine Electronics Inc.");
        companies.put(0x0419, "Novalogy LTD");
        companies.put(0x041A, "Friday Labs Limited");
        companies.put(0x041B, "OrthoAccel Technologies");
        companies.put(0x041C, "WaterGuru, Inc.");
        companies.put(0x041D, "Benning Elektrotechnik und Elektronik GmbH & Co. KG");
        companies.put(0x041E, "Dell Computer Corporation");
        companies.put(0x041F, "Kopin Corporation");
        companies.put(0x0420, "TecBakery GmbH");
        companies.put(0x0421, "Backbone Labs, Inc.");
        companies.put(0x0422, "DELSEY SA");
        companies.put(0x0423, "Chargifi Limited");
        companies.put(0x0424, "Trainesense Ltd.");
        companies.put(0x0425, "Unify Software and Solutions GmbH & Co. KG");
        companies.put(0x0426, "Husqvarna AB");
        companies.put(0x0427, "Focus fleet and fuel management inc");
        companies.put(0x0428, "SmallLoop, LLC");
        companies.put(0x0429, "Prolon Inc.");
        companies.put(0x042A, "BD Medical");
        companies.put(0x042B, "iMicroMed Incorporated");
        companies.put(0x042C, "Ticto N.V.");
        companies.put(0x042D, "Meshtech AS");
        companies.put(0x042E, "MemCachier Inc.");
        companies.put(0x042F, "Danfoss A/S");
        companies.put(0x0430, "SnapStyk Inc.");
        companies.put(0x0431, "Amway Corporation");
        companies.put(0x0432, "Silk Labs, Inc.");
        companies.put(0x0433, "Pillsy Inc.");
        companies.put(0x0434, "Hatch Baby, Inc.");
        companies.put(0x0435, "Blocks Wearables Ltd.");
        companies.put(0x0436, "Drayson Technologies (Europe) Limited");
        companies.put(0x0437, "eBest IOT Inc.");
        companies.put(0x0438, "Helvar Ltd");
        companies.put(0x0439, "Radiance Technologies");
        companies.put(0x043A, "Nuheara Limited");
        companies.put(0x043B, "Appside co., ltd.");
        companies.put(0x043C, "DeLaval");
        companies.put(0x043D, "Coiler Corporation");
        companies.put(0x043E, "Thermomedics, Inc.");
        companies.put(0x043F, "Tentacle Sync GmbH");
        companies.put(0x0440, "Valencell, Inc.");
        companies.put(0x0441, "iProtoXi Oy");
        companies.put(0x0442, "SECOM CO., LTD.");
        companies.put(0x0443, "Tucker International LLC");
        companies.put(0x0444, "Metanate Limited");
        companies.put(0x0445, "Kobian Canada Inc.");
        companies.put(0x0446, "NETGEAR, Inc.");
        companies.put(0x0447, "Fabtronics Australia Pty Ltd");
        companies.put(0x0448, "Grand Centrix GmbH");
        companies.put(0x0449, "1UP USA.com llc");
        companies.put(0x044A, "SHIMANO INC.");
        companies.put(0x044B, "Nain Inc.");
        companies.put(0x044C, "LifeStyle Lock, LLC");
        companies.put(0x044D, "VEGA Grieshaber KG");
        companies.put(0x044E, "Xtrava Inc.");
        companies.put(0x044F, "TTS Tooltechnic Systems AG & Co. KG");
        companies.put(0x0450, "Teenage Engineering AB");
        companies.put(0x0451, "Tunstall Nordic AB");
        companies.put(0x0452, "Svep Design Center AB");
        companies.put(0x0453, "GreenPeak Technologies BV");
        companies.put(0x0454, "Sphinx Electronics GmbH & Co KG");
        companies.put(0x0455, "Atomation");
        companies.put(0x0456, "Nemik Consulting Inc");
        companies.put(0x0457, "RF INNOVATION");
        companies.put(0x0458, "Mini Solution Co., Ltd.");
        companies.put(0x0459, "Lumenetix, Inc");
        companies.put(0x045A, "2048450 Ontario Inc");
        companies.put(0x045B, "SPACEEK LTD");
        companies.put(0x045C, "Delta T Corporation");
        companies.put(0x045D, "Boston Scientific Corporation");
        companies.put(0x045E, "Nuviz, Inc.");
        companies.put(0x045F, "Real Time Automation, Inc.");
        companies.put(0x0460, "Kolibree");
        companies.put(0x0461, "vhf elektronik GmbH");
        companies.put(0x0462, "Bonsai Systems GmbH");
        companies.put(0x0463, "Fathom Systems Inc.");
        companies.put(0x0464, "Bellman & Symfon");
        companies.put(0x0465, "International Forte Group LLC");
        companies.put(0x0466, "CycleLabs Solutions inc.");
        companies.put(0x0467, "Codenex Oy");
        companies.put(0x0468, "Kynesim Ltd");
        companies.put(0x0469, "Palago AB");
        companies.put(0x046A, "INSIGMA INC.");
        companies.put(0x046B, "PMD Solutions");
        companies.put(0x046C, "Qingdao Realtime Technology Co., Ltd.");
        companies.put(0x046D, "BEGA Gantenbrink-Leuchten KG");
        companies.put(0x046E, "Pambor Ltd.");
        companies.put(0x046F, "Develco Products A/S");
        companies.put(0x0470, "iDesign s.r.l.");
        companies.put(0x0471, "TiVo Corp");
        companies.put(0x0472, "Control-J Pty Ltd");
        companies.put(0x0473, "Steelcase, Inc.");
        companies.put(0x0474, "iApartment co., ltd.");
        companies.put(0x0475, "Icom inc.");
        companies.put(0x0476, "Oxstren Wearable Technologies Private Limited");
        companies.put(0x0477, "Blue Spark Technologies");
        companies.put(0x0478, "FarSite Communications Limited");
        companies.put(0x0479, "mywerk system GmbH");
        companies.put(0x047A, "Sinosun Technology Co., Ltd.");
        companies.put(0x047B, "MIYOSHI ELECTRONICS CORPORATION");
        companies.put(0x047C, "POWERMAT LTD");
        companies.put(0x047D, "Occly LLC");
        companies.put(0x047E, "OurHub Dev IvS");
        companies.put(0x047F, "Pro-Mark, Inc.");
        companies.put(0x0480, "Dynometrics Inc.");
        companies.put(0x0481, "Quintrax Limited");
        companies.put(0x0482, "POS Tuning Udo Vosshenrich GmbH & Co. KG");
        companies.put(0x0483, "Multi Care Systems B.V.");
        companies.put(0x0484, "Revol Technologies Inc");
        companies.put(0x0485, "SKIDATA AG");
        companies.put(0x0486, "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME");
        companies.put(0x0487, "Centrica Connected Home");
        companies.put(0x0488, "Automotive Data Solutions Inc");
        companies.put(0x0489, "Igarashi Engineering");
        companies.put(0x048A, "Taelek Oy");
        companies.put(0x048B, "CP Electronics Limited");
        companies.put(0x048C, "Vectronix AG");
        companies.put(0x048D, "S-Labs Sp. z o.o.");
        companies.put(0x048E, "Companion Medical, Inc.");
        companies.put(0x048F, "BlueKitchen GmbH");
        companies.put(0x0490, "Matting AB");
        companies.put(0x0491, "SOREX - Wireless Solutions GmbH");
        companies.put(0x0492, "ADC Technology, Inc.");
        companies.put(0x0493, "Lynxemi Pte Ltd");
        companies.put(0x0494, "SENNHEISER electronic GmbH & Co. KG");
        companies.put(0x0495, "LMT Mercer Group, Inc");
        companies.put(0x0496, "Polymorphic Labs LLC");
        companies.put(0x0497, "Cochlear Limited");
        companies.put(0x0498, "METER Group, Inc. USA");
        companies.put(0x0499, "Ruuvi Innovations Ltd.");
        companies.put(0x049A, "Situne AS");
        companies.put(0x049B, "nVisti, LLC");
        companies.put(0x049C, "DyOcean");
        companies.put(0x049D, "Uhlmann & Zacher GmbH");
        companies.put(0x049E, "AND!XOR LLC");
        companies.put(0x049F, "tictote AB");
        companies.put(0x04A0, "Vypin, LLC");
        companies.put(0x04A1, "PNI Sensor Corporation");
        companies.put(0x04A2, "ovrEngineered, LLC");
        companies.put(0x04A3, "GT-tronics HK Ltd");
        companies.put(0x04A4, "Herbert Waldmann GmbH & Co. KG");
        companies.put(0x04A5, "Guangzhou FiiO Electronics Technology Co.,Ltd");
        companies.put(0x04A6, "Vinetech Co., Ltd");
        companies.put(0x04A7, "Dallas Logic Corporation");
        companies.put(0x04A8, "BioTex, Inc.");
        companies.put(0x04A9, "DISCOVERY SOUND TECHNOLOGY, LLC");
        companies.put(0x04AA, "LINKIO SAS");
        companies.put(0x04AB, "Harbortronics, Inc.");
        companies.put(0x04AC, "Undagrid B.V.");
        companies.put(0x04AD, "Shure Inc");
        companies.put(0x04AE, "ERM Electronic Systems LTD");
        companies.put(0x04AF, "BIOROWER Handelsagentur GmbH");
        companies.put(0x04B0, "Weba Sport und Med. Artikel GmbH");
        companies.put(0x04B1, "Kartographers Technologies Pvt. Ltd.");
        companies.put(0x04B2, "The Shadow on the Moon");
        companies.put(0x04B3, "mobike (Hong Kong) Limited");
        companies.put(0x04B4, "Inuheat Group AB");
        companies.put(0x04B5, "Swiftronix AB");
        companies.put(0x04B6, "Diagnoptics Technologies");
        companies.put(0x04B7, "Analog Devices, Inc.");
        companies.put(0x04B8, "Soraa Inc.");
        companies.put(0x04B9, "CSR Building Products Limited");
        companies.put(0x04BA, "Crestron Electronics, Inc.");
        companies.put(0x04BB, "Neatebox Ltd");
        companies.put(0x04BC, "Draegerwerk AG & Co. KGaA");
        companies.put(0x04BD, "AlbynMedical");
        companies.put(0x04BE, "Averos FZCO");
        companies.put(0x04BF, "VIT Initiative, LLC");
        companies.put(0x04C0, "Statsports International");
        companies.put(0x04C1, "Sospitas, s.r.o.");
        companies.put(0x04C2, "Dmet Products Corp.");
        companies.put(0x04C3, "Mantracourt Electronics Limited");
        companies.put(0x04C4, "TeAM Hutchins AB");
        companies.put(0x04C5, "Seibert Williams Glass, LLC");
        companies.put(0x04C6, "Insta GmbH");
        companies.put(0x04C7, "Svantek Sp. z o.o.");
        companies.put(0x04C8, "Shanghai Flyco Electrical Appliance Co., Ltd.");
        companies.put(0x04C9, "Thornwave Labs Inc");
        companies.put(0x04CA, "Steiner-Optik GmbH");
        companies.put(0x04CB, "Novo Nordisk A/S");
        companies.put(0x04CC, "Enflux Inc.");
        companies.put(0x04CD, "Safetech Products LLC");
        companies.put(0x04CE, "GOOOLED S.R.L.");
        companies.put(0x04CF, "DOM Sicherheitstechnik GmbH & Co. KG");
        companies.put(0x04D0, "Olympus Corporation");
        companies.put(0x04D1, "KTS GmbH");
        companies.put(0x04D2, "Anloq Technologies Inc.");
        companies.put(0x04D3, "Queercon, Inc");
        companies.put(0x04D4, "5th Element Ltd");
        companies.put(0x04D5, "Gooee Limited");
        companies.put(0x04D6, "LUGLOC LLC");
        companies.put(0x04D7, "Blincam, Inc.");
        companies.put(0x04D8, "FUJIFILM Corporation");
        companies.put(0x04D9, "RandMcNally");
        companies.put(0x04DA, "Franceschi Marina snc");
        companies.put(0x04DB, "Engineered Audio, LLC.");
        companies.put(0x04DC, "IOTTIVE (OPC) PRIVATE LIMITED");
        companies.put(0x04DD, "4MOD Technology");
        companies.put(0x04DE, "Lutron Electronics Co., Inc.");
        companies.put(0x04DF, "Emerson");
        companies.put(0x04E0, "Guardtec, Inc.");
        companies.put(0x04E1, "REACTEC LIMITED");
        companies.put(0x04E2, "EllieGrid");
        companies.put(0x04E3, "Under Armour");
        companies.put(0x04E4, "Woodenshark");
        companies.put(0x04E5, "Avack Oy");
        companies.put(0x04E6, "Smart Solution Technology, Inc.");
        companies.put(0x04E7, "REHABTRONICS INC.");
        companies.put(0x04E8, "STABILO International");
        companies.put(0x04E9, "Busch Jaeger Elektro GmbH");
        companies.put(0x04EA, "Pacific Bioscience Laboratories, Inc");
        companies.put(0x04EB, "Bird Home Automation GmbH");
        companies.put(0x04EC, "Motorola Solutions");
        companies.put(0x04ED, "R9 Technology, Inc.");
        companies.put(0x04EE, "Auxivia");
        companies.put(0x04EF, "DaisyWorks, Inc");
        companies.put(0x04F0, "Kosi Limited");
        companies.put(0x04F1, "Theben AG");
        companies.put(0x04F2, "InDreamer Techsol Private Limited");
        companies.put(0x04F3, "Cerevast Medical");
        companies.put(0x04F4, "ZanCompute Inc.");
        companies.put(0x04F5, "Pirelli Tyre S.P.A.");
        companies.put(0x04F6, "McLear Limited");
        companies.put(0x04F7, "Shenzhen Huiding Technology Co.,Ltd.");
        companies.put(0x04F8, "Convergence Systems Limited");
        companies.put(0x04F9, "Interactio");
        companies.put(0x04FA, "Androtec GmbH");
        companies.put(0x04FB, "Benchmark Drives GmbH & Co. KG");
        companies.put(0x04FC, "SwingLync L. L. C.");
        companies.put(0x04FD, "Tapkey GmbH");
        companies.put(0x04FE, "Woosim Systems Inc.");
        companies.put(0x04FF, "Microsemi Corporation");
        companies.put(0x0500, "Wiliot LTD.");
        companies.put(0x0501, "Polaris IND");
        companies.put(0x0502, "Specifi-Kali LLC");
        companies.put(0x0503, "Locoroll, Inc");
        companies.put(0x0504, "PHYPLUS Inc");
        companies.put(0x0505, "Inplay Technologies LLC");
        companies.put(0x0506, "Hager");
        companies.put(0x0507, "Yellowcog");
        companies.put(0x0508, "Axes System sp. z o. o.");
        companies.put(0x0509, "myLIFTER Inc.");
        companies.put(0x050A, "Shake-on B.V.");
        companies.put(0x050B, "Vibrissa Inc.");
        companies.put(0x050C, "OSRAM GmbH");
        companies.put(0x050D, "TRSystems GmbH");
    }
    public static String lookup(Integer id, String defaultName) {
        String name = companies.get(id);
        return name == null ? defaultName : name;
    }
}

